name: Shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    steps:
      _ name: echo a string
        run: echo "Hello worl"
      - name: multline  script
        run: |
          python3 -v
          touch my_file_with_worflow.py
          ls -l
